module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        osmosiszonealto: "var(--osmosiszonealto)",
        osmosiszoneamaranth: "var(--osmosiszoneamaranth)",
        osmosiszoneanakiwa: "var(--osmosiszoneanakiwa)",
        "osmosiszoneazure-radiance": "var(--osmosiszoneazure-radiance)",
        osmosiszoneblack: "var(--osmosiszoneblack)",
        "osmosiszonebleach-white": "var(--osmosiszonebleach-white)",
        "osmosiszoneblue-ribbon": "var(--osmosiszoneblue-ribbon)",
        "osmosiszonebrick-red": "var(--osmosiszonebrick-red)",
        "osmosiszonebright-turquoise": "var(--osmosiszonebright-turquoise)",
        osmosiszonebuttercup: "var(--osmosiszonebuttercup)",
        osmosiszonecharade: "var(--osmosiszonecharade)",
        osmosiszonechiffon: "var(--osmosiszonechiffon)",
        osmosiszonecinnabar: "var(--osmosiszonecinnabar)",
        "osmosiszonecod-gray": "var(--osmosiszonecod-gray)",
        osmosiszonecoral: "var(--osmosiszonecoral)",
        "osmosiszonecoral-red": "var(--osmosiszonecoral-red)",
        "osmosiszonecornflower-blue-75": "var(--osmosiszonecornflower-blue-75)",
        "osmosiszonecurious-blue": "var(--osmosiszonecurious-blue)",
        "osmosiszonedeep-sapphire": "var(--osmosiszonedeep-sapphire)",
        osmosiszonedisco: "var(--osmosiszonedisco)",
        "osmosiszonedodger-blue": "var(--osmosiszonedodger-blue)",
        osmosiszonedune: "var(--osmosiszonedune)",
        "osmosiszoneebony-clay": "var(--osmosiszoneebony-clay)",
        "osmosiszoneelectric-violet": "var(--osmosiszoneelectric-violet)",
        "osmosiszoneenergy-yellow": "var(--osmosiszoneenergy-yellow)",
        osmosiszoneflamingo: "var(--osmosiszoneflamingo)",
        osmosiszonegeraldine: "var(--osmosiszonegeraldine)",
        "osmosiszonegray-suit": "var(--osmosiszonegray-suit)",
        "osmosiszonehokey-pokey": "var(--osmosiszonehokey-pokey)",
        "osmosiszoneinch-worm": "var(--osmosiszoneinch-worm)",
        "osmosiszoneinternational-orange":
          "var(--osmosiszoneinternational-orange)",
        osmosiszonejaffa: "var(--osmosiszonejaffa)",
        osmosiszonejagger: "var(--osmosiszonejagger)",
        "osmosiszonejordy-blue": "var(--osmosiszonejordy-blue)",
        "osmosiszonelightning-yellow": "var(--osmosiszonelightning-yellow)",
        osmosiszonemalibu: "var(--osmosiszonemalibu)",
        osmosiszonemandy: "var(--osmosiszonemandy)",
        "osmosiszonemardi-gras": "var(--osmosiszonemardi-gras)",
        "osmosiszonemedium-purple": "var(--osmosiszonemedium-purple)",
        osmosiszonemerlot: "var(--osmosiszonemerlot)",
        osmosiszonemirage: "var(--osmosiszonemirage)",
        "osmosiszonemorning-glory": "var(--osmosiszonemorning-glory)",
        "osmosiszonemountain-meadow": "var(--osmosiszonemountain-meadow)",
        osmosiszonemulberry: "var(--osmosiszonemulberry)",
        osmosiszoneorange: "var(--osmosiszoneorange)",
        osmosiszoneparchment: "var(--osmosiszoneparchment)",
        osmosiszoneperfume: "var(--osmosiszoneperfume)",
        osmosiszoneperiwinkle: "var(--osmosiszoneperiwinkle)",
        "osmosiszonepersian-blue-80": "var(--osmosiszonepersian-blue-80)",
        "osmosiszonepickled-bluewood": "var(--osmosiszonepickled-bluewood)",
        "osmosiszonepicton-blue": "var(--osmosiszonepicton-blue)",
        osmosiszoneplum: "var(--osmosiszoneplum)",
        osmosiszonepurple: "var(--osmosiszonepurple)",
        osmosiszonerazzmatazz: "var(--osmosiszonerazzmatazz)",
        "osmosiszonered-violet": "var(--osmosiszonered-violet)",
        "osmosiszoneripe-lemon": "var(--osmosiszoneripe-lemon)",
        osmosiszonerose: "var(--osmosiszonerose)",
        "osmosiszoneroyal-blue": "var(--osmosiszoneroyal-blue)",
        "osmosiszoneroyal-blue-70": "var(--osmosiszoneroyal-blue-70)",
        "osmosiszonestorm-gray": "var(--osmosiszonestorm-gray)",
        osmosiszonestratos: "var(--osmosiszonestratos)",
        osmosiszonesunflower: "var(--osmosiszonesunflower)",
        "osmosiszonetall-poppy": "var(--osmosiszonetall-poppy)",
        "osmosiszonetree-poppy": "var(--osmosiszonetree-poppy)",
        osmosiszonetuna: "var(--osmosiszonetuna)",
        osmosiszoneviolet: "var(--osmosiszoneviolet)",
        osmosiszonewhite: "var(--osmosiszonewhite)",
        "osmosiszonewild-sand": "var(--osmosiszonewild-sand)",
        "osmosiszoneyour-pink": "var(--osmosiszoneyour-pink)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        description: "var(--description-font-family)",
        "osmosis-zone-inter-medium":
          "var(--osmosis-zone-inter-medium-font-family)",
        subtitle: "var(--subtitle-font-family)",
        "subtitle-48": "var(--subtitle-48-font-family)",
        text: "var(--text-font-family)",
        "title-64": "var(--title-64-font-family)",
        "title-72": "var(--title-72-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
